apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: release-name-app-server
  labels:
    app.kubernetes.io/name: app-server
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "1.16.0"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: release-name-app-server
  minReplicas: 1
  maxReplicas: 100
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 80